### ISSUE TITLE
Loading pre-trained skinning models gives size mismatch error

### ISSUE THREAD

**Issue by npateel** [zhan-xu/RigNet#22]
I'm currently trying to load the Skinning model using `run_skinning.py` using the checkpoints given in the README, but the parameter sizes appear to be mismatched. Is there any sort of pre-processing / commands I need to do in order to load from the checkpoint?

I've attached the error trace below.

```python
=> loading checkpoint 'checkpoints/skinnet/model_best.pth.tar'
Traceback (most recent call last):
  File "run_skinning.py", line 248, in <module>
    main(parser.parse_args())
  File "run_skinning.py", line 109, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SKINNET:
        size mismatch for multi_layer_tranform1.0.0.weight: copying a param with shape torch.Size([128, 43]) from checkpoint, the shape in current model is torch.Size([128, 33]).
```

**Comment by zhan-xu** [comment]
You will need to pass --Lf and --Dg to activate these two options.
