### ISSUE TITLE
Issue running quick_start.py, The specified procedure could not be found

### ISSUE THREAD

**Issue by shshwdr** [zhan-xu/RigNet#25]
I'm using Windows 64, when I try to run quick_start.py, I got this error message pop up and this traceback:
![error quick start](https://user-images.githubusercontent.com/8190623/98425938-e0bc3980-204b-11eb-8d12-10c3dcbc029d.JPG)

(rignet_env) C:\Users\csviv\Desktop\github\RigNet>python quick_start.py
Traceback (most recent call last):
  File "quick_start.py", line 17, in <module>
    from torch_geometric.data import Data
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch_sparse\__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "C:\Users\csviv\Anaconda3\envs\rignet_env\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

**Comment by zhan-xu** [comment]
could you please provide the version of cuda-toolkit you are using, as well as the versions of the installed pytorch, torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, torch-geometric?

**Comment by shshwdr** [comment]
this are the versions I got:
CUDA 11.1
cuDNN v8.0.4
Pytorch: 1.7.0
Torch-scatter-2.0.5
Torch-sparse-0.6.8
Torch-cluster-1.5.8
Torch-spline-conv-1.2.0
torch-geometric-1.6.1

These are the commands I used:
pip install numpy scipy matplotlib tensorboard open3d==0.9.0 opencv-python
pip install Rtree‑0.9.4‑cp37‑cp37m‑win_amd64.whl
pip install trimesh[easy]
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-geometric

T

**Comment by zhan-xu** [comment]
Thanks for sharing the details. It looks like you didn't install the correct version of torch-* corresponding to your cuda.

You are using cuda 11, so you will need to install torch-* for cuda110. This means the command should be modified into 

```
pip install torch-scatter==latest+cu110 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-sparse==latest+cu110 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-cluster==latest+cu110 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-spline-conv==latest+cu110 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
```
Please also see https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html for installation instructions.
