### ISSUE TITLE
Issue running run_joint_pretrain.py

### ISSUE THREAD

**Issue by Bin-Ji** [zhan-xu/RigNet#28]
Dear authors,
Thanks for the great paper !
I have some problem about training, could you please explain the file path of DATASET_DIR in detail? I have not used the dataset of torch.geometric before. Take the training set as example, should the pre-processed data you have provided in readme  be displayed this way: DATASET_DIR/train/raw/...txt,...binvox?

**Comment by zhan-xu** [comment]
Hi. Once you've downloaded the pre-processed data, it contains sub-folders "obj", "obj_remesh", etc. Then, after running gen_dataset.py, it will create sub-folders "train", "val", "test".

At this point you don't need to more extra work. You can then run `run_joint_pretrain.py`. pytorch-geometric will automatically create a sub-folder called "processed" in each of the "train", "val", "test" folders, and create a ready-to-use compressed file containing all data inside this "processed" sub-folder. 

The file hierarchy looks like:
--ModelResource_RigNetv1_preproccessed
    --train
         --processed
              --train_skeleton_data.pt
              --train_skinning_data.pt
         --*_j.txt
         --*_v.txt
         ...
    --val
         --processed
              --val_skeleton_data.pt
              --val_skinning_data.pt
         --*_j.txt
         --*_v.txt
    --test
         --processed
              --test_skeleton_data.pt
              --test_skinning_data.pt
         --*_j.txt
         --*_v.txt
    --obj
    --obj_remesh
    --rig_info
    ...

**Comment by Bin-Ji** [comment]
thank you for your response!
I did as your described, but it reported an error as  follow:
'''
preprecessing data complete: 0.0000%
Traceback (most recent call last):
  File "run_joint_pretrain.py", line 212, in <module>
    main(parser.parse_args())
  File "run_joint_pretrain.py", line 80, in main
    train_loader = DataLoader(GraphDataset(root=args.train_folder), batch_size=args.train_batch, shuffle=True, follow_batch=['joints'])
  File "/media/Diske/projects/RigNet/datasets/skeleton_dataset.py", line 42, in __init__
    super(GraphDataset, self).__init__(root)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/media/Diske/projects/RigNet/datasets/skeleton_dataset.py", line 86, in process
    v = np.loadtxt(v_filename)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/numpy/lib/npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ModelResource_RigNetv1_preproccessed/train/raw/ModelResource_RigNetv1_preproccessed/train/17606_v.txt not found.
'''



It seems that in file "skeleton_dataset.py",line 83, "self.raw_paths"  is not what we want, so I replace it with "self.raw_file_names" , and put the training data into the automatically created  sub-folder "raw" file then run "run_joint_pretrain.py" and generate "pre_filter.pt", "pre_transform.pt" and "train_skeleton_data.pt" but not "train_skinning_data.pt" , and there are still something wrong like:

```
  File "run_joint_pretrain.py", line 81, in main
    val_loader = DataLoader(GraphDataset(root=args.val_folder), batch_size=args.test_batch, shuffle=False, follow_batch=['joints'])
  File "/media/Diske/projects/RigNet_old/datasets/skeleton_dataset.py", line 42, in __init__
    super(GraphDataset, self).__init__(root)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 92, in __init__
    self._process()
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/media/Diske/projects/RigNet_old/datasets/skeleton_dataset.py", line 128, in process
    data, slices = self.collate(data_list)
  File "/media/Diskd/anaconda3/envs/VIBE/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 92, in collate
    keys = data_list[0].keys
IndexError: list index out of range

```

**Comment by zhan-xu** [comment]
Did you set --train_folder/val_folder/test_folder correctly? In Line 47 of skeleton_dataset.py, the raw_file_names is defined as 
```
raw_v_filelist = glob.glob(os.path.join(self.root, '*_v.txt'))
```
where root is the train_folder/val_folder/test_folder you set. All *_v.txt files are supposed to be in the train_folder/val_folder/test_folder, and "raw" folder is not supposed to be created.

"train_skinning_data.pt" will be generate when you run "run_skinning.py"

**Comment by Bin-Ji** [comment]
thank you for your response!

I followed what you said, but the `$raw$` folder was  still created automatically. So i  move these `$*\_v.txt$`,`$*\_j.txt$`... into the "raw" folder affiliated to train_folder/val_folder/test_folder, and two changes have been made to the code `$skeleton_dataset.py$` : line 47: `$raw_v_filelist = glob.glob(os.path.join(self.root,'raw', '*_v.txt'))$` and line 83:`$self.raw_file_names$`
