### ISSUE TITLE
[Open3D WARNING] Read OBJ failed: Cannot open file [quick_start/17872_remesh.obj]

### ISSUE THREAD

**Issue by cloudweather** [zhan-xu/RigNet#5]
Hi. I got the following error when I ran `python quick_start.py`

```
loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 17872
[Open3D WARNING] Read OBJ failed: Cannot open file [quick_start/17872_remesh.obj]

     gathering topological edges.
Traceback (most recent call last):
  File "quick_start.py", line 390, in <module>
    data, vox, surface_geodesic = create_single_data(mesh_filename)
  File "quick_start.py", line 56, in create_single_data
    tpl_e = get_tpl_edges(mesh_v, mesh_f).T
  File "/home/cloud/youtube/rignet/RigNet/gen_dataset.py", line 33, in get_tpl_edges
    edge_index = np.concatenate(edge_index, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

How can I fix this? Thank you~

**Comment by zhan-xu** [comment]
I tried this and it worked fine. It seems from the error that it cannot find that OBJ file. Could you check your current working path? This OBJ file is in the folder "quick_start ", so maybe you try to make the path correct?

**Comment by cloudweather** [comment]
I realized I need to change the model id inside quick_start.py
But even after I changed the model ID in quick_start.py I got another error:
```
loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 1347
     gathering topological edges.
     calculating surface geodesic matrix.
surface geodesic calculation: 6.1555070877075195 seconds
     gathering geodesic edges.

--- [binvox] mesh voxelizer, version 1.26, build #644 on 2017/10/22 15:19:22
--- written by Patrick Min, 2004-2017

  will use offscreen pbuffer instead of onscreen window
loading model file...
MeshFileIdentifier::*create_mesh_file(quick_start/1347_remesh.obj)
ObjMeshFile::load(quick_start/1347_remesh.obj)
9800 quick_start/1347_remesh.obj
  9801 lines read
Read 4842 faces, 2478 vertices.
Mesh memory use is 3040 KB (2 MB)
  Mesh::normalize, bounding box: [-0.422843, 0, -0.5, 1] - [0.422843, 0.70882, 0.5, 1]
    longest length: 1
  normalization transform:
  (1) translate [0.422843, -0, 0.5, 1], (2) scale 1, (3) translate [0, 0, 0]
freeglut (./binvox): failed to open display ''
Traceback (most recent call last):
  File "quick_start.py", line 390, in <module>
    data, vox, surface_geodesic = create_single_data(mesh_filename)
  File "quick_start.py", line 76, in create_single_data
    with open(mesh_filaname.replace('.obj', '.binvox'), 'rb') as fvox:
FileNotFoundError: [Errno 2] No such file or directory: 'quick_start/1347_remesh.binvox'
```
Here's a screenshot of my files:
![qwrfaxc](https://user-images.githubusercontent.com/29135514/88502481-2440e980-d001-11ea-989f-2a76c43cf49d.PNG)

and also how can we test out our own 3D mesh? Do we just need one single .obj file? 
Thank you!

**Comment by Danscap** [comment]
@zhan-xu @cloudweather  I am having the same issue, well the last line of the error is the same.

loading all networks...
     joint prediction network loaded.
     root prediction network loaded.
     connection prediction network loaded.
     skinning prediction network loaded.
creating data for model ID 17872
     gathering topological edges.
     calculating surface geodesic matrix.
surface geodesic calculation: 6.807190418243408 seconds
     gathering geodesic edges.
'.' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "quick_start.py", line 390, in <module>
    data, vox, surface_geodesic = create_single_data(mesh_filename)
  File "quick_start.py", line 76, in create_single_data
    with open(mesh_filaname.replace('.obj', '.binvox'), 'rb') as fvox:
FileNotFoundError: [Errno 2] No such file or directory: 'quick_start/17872_remesh.binvox'


I'm not sure how your error code is different from mine when they both end with the same error.

**Comment by zhan-xu** [comment]
Based on https://unix.stackexchange.com/questions/155418/binvox-not-working-on-a-headless-linux-server, I suggest you try to install Xvfb. In the code I use binvox (https://www.patrickmin.com/binvox/) to voxelize the model interior, and the reported error comes from the error of calling binvox.

**Comment by zhan-xu** [comment]
And yes, you need only input a single model, with vertices number between 1K to 5K (since we trained on models with such resolution). You can immigrate to original resolution with nearest-neighbor. Look at the very end (line 402-line 410) of quick_start.py.

**Comment by Danscap** [comment]
@zhan-xu Thank you. For windows, we must download binvox and change the quick_start.py to use it?

I see that starting at line 75 uses the program:

![image](https://user-images.githubusercontent.com/34867523/88556536-20a86500-cff7-11ea-8fd1-84d8785c1de0.png)



Also I was not aware that models should be between 1k-5k vertices. I frequently work with humanoid models that number > 20k vertices. I could bring this number down with Blender's decimate modifier. Would 6-10k still produce working results?

**Comment by zhan-xu** [comment]
@Danscap Yes. I attached a Linux version of binvox under the root folder, but you are right, to use it under Windows, you will have to download the windows version from here https://www.patrickmin.com/binvox/download.php?id=2, and change the line as you showed above to "binvox.exe -d 88 -pb".

It is better to keep vertices of test models between 1K-5K since the networks are trained on such data. you may try with 6-10K vertices, but it will become very slow (I have a volumetric geodesic distance calculation which shoots rays and finds intersection on the surface. This step is time-consuming for now). You can first decimate the mesh and name is as xxx_remesh.obj, also name the original mesh with high-res as xxx_ori.obj, just as the examples I put in the quick_start folder. Lines 404-406 will immigrate the results back to the original resolution.

**Comment by zhenqingkai** [comment]
Great work, it works fine.

**Comment by jiandandian2** [comment]
@Danscap
i have the same problem
![image](https://user-images.githubusercontent.com/33227739/92424217-4d36cb80-f1b6-11ea-9e5e-e01697b3d765.png)
then i run the code : apt-get install xvfb , and i still get the same problem.
how did you solve it ?

**Comment by jiandandian2** [comment]
@ Danscapi run the code on server, ubuntu18

**Comment by zhan-xu** [comment]
Hi, from the output, seems binvox is not properly called. The error is the it cannot find "libGLU.so".

Could you try https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1

**Comment by jiandandian2** [comment]
> Hi, from the output, seems binvox is not properly called. The error is the it cannot find "libGLU.so".
> 
> Could you try https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1 ?

it seems work,  but i get another issue, 'freeglut (./binvox): failed to open display ':25''
![image](https://user-images.githubusercontent.com/33227739/92428167-f5519200-f1c0-11ea-9448-c592e558a261.png)

**Comment by zhan-xu** [comment]
The most related answer I can find is this: https://unix.stackexchange.com/questions/155418/binvox-not-working-on-a-headless-linux-server?rq=1

Since you have already installed Xvfb, could you try to configure as they suggested? You might need to add a "&" to the code.
(Line 94 in quick_start.py, change to `os.system("./binvox -d 88 -pb &" + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))` as they suggested.

**Comment by jiandandian2** [comment]
> The most related answer I can find is this: https://unix.stackexchange.com/questions/155418/binvox-not-working-on-a-headless-linux-server?rq=1
> 
> Since you have already installed Xvfb, could you try to configure as they suggested? You might need to add a "&" to the code.
> (Line 94 in quick_start.py, change to `os.system("./binvox -d 88 -pb &" + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))` as they suggested.

![Uploading 屏幕快照 2020-09-11 上午11.08.39.png…]()

still got mistakes, I'm so sad...

**Comment by jiandandian2** [comment]
> The most related answer I can find is this: https://unix.stackexchange.com/questions/155418/binvox-not-working-on-a-headless-linux-server?rq=1
> 
> Since you have already installed Xvfb, could you try to configure as they suggested? You might need to add a "&" to the code.
> (Line 94 in quick_start.py, change to `os.system("./binvox -d 88 -pb &" + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))` as they suggested.


![屏幕快照 2020-09-11 上午11 08 39](https://user-images.githubusercontent.com/33227739/92918324-e50c1200-f461-11ea-9bf5-2428b0b74b28.png)


still got mistakes, I'm so sad...

**Comment by zhan-xu** [comment]
I saw a permission deny error from binvox. Could you try directly from the terminal "./binvox -d 88 -pb quick_start/17872_remesh.obj"? So that the error will be more clear. Maybe you need a "sudo" before it.

**Comment by jiandandian2** [comment]
> I saw a permission deny error from binvox. Could you try directly from the terminal "./binvox -d 88 -pb quick_start/17872_remesh.obj"? So that the error will be more clear. Maybe you need a "sudo" before it.

it says pbuffers not available

![屏幕快照 2020-09-12 下午3 50 12](https://user-images.githubusercontent.com/33227739/92990511-a92f8600-f50f-11ea-840e-0e319a65169a.png)

**Comment by dongfangliu** [comment]
> > I saw a permission deny error from binvox. Could you try directly from the terminal "./binvox -d 88 -pb quick_start/17872_remesh.obj"? So that the error will be more clear. Maybe you need a "sudo" before it.
> 
> it says pbuffers not available
> 
> ![屏幕快照 2020-09-12 下午3 50 12](https://user-images.githubusercontent.com/33227739/92990511-a92f8600-f50f-11ea-840e-0e319a65169a.png)

Yes, I met the same problem, when it goes to pbuffers, my gui suddenly restart.

**Comment by dongfangliu** [comment]
> > > I saw a permission deny error from binvox. Could you try directly from the terminal "./binvox -d 88 -pb quick_start/17872_remesh.obj"? So that the error will be more clear. Maybe you need a "sudo" before it.
> > 
> > 
> > it says pbuffers not available
> > ![屏幕快照 2020-09-12 下午3 50 12](https://user-images.githubusercontent.com/33227739/92990511-a92f8600-f50f-11ea-840e-0e319a65169a.png)
> 
> Yes, I met the same problem, when it goes to pbuffers, my gui suddenly restart.

Oh that's cool, if I remove `-pb` parameter, renders onscreen is fully ok. I guess `pbuffer is not available` is caused by my usage of a remote desktop like anydesk which already occupies the pbuffer. 
I will check when I come to my desktop  face2face.

**Comment by dongfangliu** [comment]
Cool, you have to just remove the `-pb` parameter in quick-start.py. Then you can run the program properly.
Thanks, I tried this code for 8 hours and finally get it to work under CUDA11.0. Haha, built all of the torch stuff from source.

**Comment by jiandandian2** [comment]
@dongfangliu thank u. i have tried this code for serverals days, =.=. I delete the pb, but i still get probelm: Badwindow

![image](https://user-images.githubusercontent.com/33227739/93034758-b6628700-f66d-11ea-9b03-f6e659343711.png)

**Comment by zhan-xu** [comment]
> > The most related answer I can find is this: https://unix.stackexchange.com/questions/155418/binvox-not-working-on-a-headless-linux-server?rq=1
> > Since you have already installed Xvfb, could you try to configure as they suggested? You might need to add a "&" to the code.
> > (Line 94 in quick_start.py, change to `os.system("./binvox -d 88 -pb &" + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))` as they suggested.
> 
> ![屏幕快照 2020-09-11 上午11 08 39](https://user-images.githubusercontent.com/33227739/92918324-e50c1200-f461-11ea-9bf5-2428b0b74b28.png)
> 
> still got mistakes, I'm so sad...

Actually this seems promising to me. Your screen shot doesn't have the command you ran. Could I take a look at what commands you ran for this?

**Comment by dongfangliu** [comment]
> @dongfangliu thank u. i have tried this code for serverals days, =.=. I delete the pb, but i still get probelm: Badwindow
> 
> ![image](https://user-images.githubusercontent.com/33227739/93035015-7354e380-f66e-11ea-914a-61fd2496bc03.png)

`./binvox -d 88  quick_start/17872_remesh.obj` Try this

**Comment by jiandandian2** [comment]
@zhan-xu
it's like this
![image](https://user-images.githubusercontent.com/33227739/93178289-9c589f80-f766-11ea-9d17-57e149fecb11.png)

**Comment by jiandandian2** [comment]
@dongfangliu yes, i input: 
./binvox -d 88 quick_start/17872_remesh.obj
it says BadWindow

![image](https://user-images.githubusercontent.com/33227739/93179608-7e8c3a00-f768-11ea-88a2-79e1090cb5d6.png)

**Comment by dongfangliu** [comment]
> @zhan-xu
> it's like this
> ![image](https://user-images.githubusercontent.com/33227739/93178289-9c589f80-f766-11ea-9d17-57e149fecb11.png)

Now I have no idea

**Comment by zhan-xu** [comment]
One quick try could be change to port to some other number rather than 25, such as 19 (https://unix.stackexchange.com/questions/9107/how-can-i-run-firefox-on-linux-headlessly-i-e-without-requiring-libgtk-x11-2-0/9118#9118).

Another thing you can try is instead of using remote desk, you can use a terminal to ssh to the remote server and see how it works. My feeling is the remote desk messes up the display devices.

**Comment by jiandandian2** [comment]
> @jiandandian2 One quick try could be changing the port to some other number rather than 25, such as 19 (https://unix.stackexchange.com/questions/9107/how-can-i-run-firefox-on-linux-headlessly-i-e-without-requiring-libgtk-x11-2-0/9118#9118).
> 
> Another thing you can try is instead of using remote desk, you can use a terminal to ssh to the remote server and see how it works. My feeling is the remote desk messes up the display devices.

it works
but it seems to stop at the predicting connectivity step, nothing for a long time 
![image](https://user-images.githubusercontent.com/33227739/95555757-da36a400-0a44-11eb-8edc-92e87a9262c9.png)

**Comment by zhan-xu** [comment]
Hi! Any updates on how to solve this problem?

**Comment by leodilla** [comment]
There might be issues with running binvox/xvfb on headless servers about how to terminate/kill the process.
I add 'xvfb-run -d' before all './binvox' in the python file and then the problem is solved.

**Comment by Mahyar-Ali** [comment]
This worked for me.

install `libglu1-mesa`
install `binvox`
install `xvfb`
create a virtual frame buffer using `Xvfb :25 -screen 0 1900x1080x16 &`
 Xvfb works fine at depths 15, 16, 24
and finally, export the display using `export DISPLAY:=25`

**Comment by visonpon** [comment]
Hi @leodilla ,I try to use xvfb-run, but get another problem, hope you help.
my command is` xvfb-run -a ./binvox -d -88 -pb`,the error is : `Error: could not create pbuffer`

**Comment by L1423** [comment]
> This worked for me.
> 
> install `libglu1-mesa` install `binvox` install `xvfb` create a virtual frame buffer using `Xvfb :25 -screen 0 1900x1080x16 &` Xvfb works fine at depths 15, 16, 24 and finally, export the display using `export DISPLAY:=25`

I used the school's computing resources. So I do not have administrator rights and do not know how to install xvfb. I do not know where xvfb is installed on the school computing platform. I don't know what to do.

**Comment by L1423** [comment]
> > This worked for me.
> > install `libglu1-mesa` install `binvox` install `xvfb` create a virtual frame buffer using `Xvfb :25 -screen 0 1900x1080x16 &` Xvfb works fine at depths 15, 16, 24 and finally, export the display using `export DISPLAY:=25`
> 
> I used the school's computing resources. So I do not have administrator rights and do not know how to install xvfb. I do not know where xvfb is installed on the school computing platform. I don't know what to do.

@zhan-xu 望解答 please answer my questions. Thank you!

**Comment by L1423** [comment]
我使用win下的binvox.exe 生成了相应的.binvox文件。应该和Linux下生成的一样吧。但是运行quick_start.py时，报错RuntimeError: Not compiled with CUDA support。有人有相同的错误吗，有什么解决的办法吗

**Comment by L1423** [comment]
> 

最后是直接按作者另一篇论文Morig的环境安装，最后成功了。应该是环境的一些依赖项没有安装到对应版本，或者缺了一些依赖项。

**Comment by tshrjn** [comment]
What worked for me:

```
sudo apt-get install libglu1-mesa # util for binvox
sudo apt-get install xvfb # for headless binvox usage
sudo apt-get install libspatialindex-dev # for rtree (part of trimesh) dependency
```
Even with xvfb, binvox doesn't support `pbuffer` - [ref](https://www.patrickmin.com/binvox/wiki/doku.php?id=no_gpu).

Try:
```
Xvfb :25 -screen 0 1900x1080x16 &
export DISPLAY=:25
./binvox -d 88 -pb quick_start/17872_remesh.obj  &
```
and 
```
Xvfb-run -a ./binvox -d 88 quick_start/17872_remesh.obj  &
```
& update [quick_start.py#L97](https://github.com/zhan-xu/RigNet/blob/master/quick_start.py#L97C16-L97C16) to:

```
os.system("xvfb-run -a ./binvox -d 88 " + mesh_filaname.replace("_remesh.obj", "_normalized.obj"))
```
